// One-off script to assemble preview.html from the modular source files.
// Not part of the deployed site — run manually after editing index.html/styles.css/app.js/data/*.json.
const fs = require("fs");
const path = require("path");

const root = __dirname;
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const css = fs.readFileSync(path.join(root, "styles.css"), "utf8");
const js = fs.readFileSync(path.join(root, "app.js"), "utf8");
const questions = fs.readFileSync(path.join(root, "data/questions.json"), "utf8");
const exercises = fs.readFileSync(path.join(root, "data/exercises.json"), "utf8");
const bestPractices = fs.readFileSync(path.join(root, "data/best-practices.json"), "utf8");

let out = html;

// Drop Google Fonts preconnect/link tags (kept as external font load — CSS/JS/data are what must be inlined).
// Replace the stylesheet link with an inline <style> block.
out = out.replace(
  /<link rel="stylesheet" href="styles\.css">/,
  `<style>\n${css}\n</style>`
);

// Replace the app.js script tag with an inline script that has JSON data
// embedded and fetch() calls swapped for the embedded data.
const inlineData = `const EMBEDDED_DATA = {\n  "data/questions.json": ${questions.trim()},\n  "data/exercises.json": ${exercises.trim()},\n  "data/best-practices.json": ${bestPractices.trim()}\n};\n`;

let inlineJs = js.replace(
  /async function fetchJson\(path\) \{[\s\S]*?\n  \}/,
  `async function fetchJson(path) {\n    return EMBEDDED_DATA[path] || [];\n  }`
);

out = out.replace(
  /<script src="app\.js"><\/script>/,
  `<script>\n${inlineData}\n${inlineJs}\n</script>`
);

// Add a small preview banner note in a comment for anyone opening the source.
out = out.replace(
  "<title>",
  "<!-- Single-file preview build: CSS, JS, and seed data inlined. Generated by build-preview.js — do not hand-edit; edit the modular sources and regenerate. -->\n<title>"
);

fs.writeFileSync(path.join(root, "preview.html"), out);
console.log("Wrote preview.html");
